server:
  port: 8082


spring:
  application:
    name: weather-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jakarta.persistence.validation.mode: none
        types:
          spatial:
            enabled: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    # ????? ???????
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agro_plan}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: always

# Weather API Configuration
weather:
  api:
    forecast-base-url: https://api.open-meteo.com/v1
    historical-base-url: https://archive-api.open-meteo.com/v1
    max-in-memory-size: 10485760  # 10MB
    historical-data-lag-days: 5
    long-period-threshold-months: 3

logging:
  level:
    org:
      springframework:
        transaction: INFO
        transaction.interceptor: TRACE
      orm:
        jpa: INFO
        jpa.JpaTransactionManager: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      omstu:
        weatherservice: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # ???????????? IP ?????? hostname
    instance-id: ${spring.application.name}:${server.port}

    register-with-eureka: true
    fetch-registry: true
