server:
  port: 8081


spring:
  application:
    name: agriculture-field-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jakarta.persistence.validation.mode: none
        types:
          spatial:
            enabled: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agro_plan}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        transaction: INFO
        transaction.interceptor: TRACE
      orm:
        jpa: INFO
        jpa.JpaTransactionManager: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

services:
  weather-service:
    url: ${WEATHER_SERVICE_URL:http://localhost:8082}
  ml-service:
    url: ${ML_SERVICE_URL:http://localhost:8000}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true  # Использовать IP вместо hostname
    instance-id: ${spring.application.name}:${server.port}

    register-with-eureka: true
    fetch-registry: true
